### ISSUE TITLE
List of meetups

### ISSUE THREAD

**Issue by BrianHicks** [stl-tech/todo#1]
This organization should list meetups (probably on stl-tech.github.io)

**Comment by booch** [comment]
Interesting idea. As a one-time co-maintainer of the SLUUG calendar, I've long wanted to automate screen-scraping all the meeting times/dates into a single central calendar. I hadn't considered crowd-sourcing it. Of course, 90% of meetings are now on Meetup.com.

**Comment by chrwei** [comment]
you can get meetup evens as ical, and some groups use google calendar which supports ical too, so for those it's a one time setup

**Comment by BrianHicks** [comment]
We've mostly solved this, actually, by adding RSS feeds into the #events channel. I'm going to close this, since it works just fine for now.
