### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by BrianHicks** [stl-tech/todo#2]
We need a logo! If someone wants to design one, I'll take almost anything. ;)

**Comment by khhuff** [comment]
Brian,
I can design a logo and send it to you this weekend. One question, is it to be incorporated as an STL-Python logo or for stl-tech?

Thanks,
Kristofer H

**Comment by BrianHicks** [comment]
@khhuff that would be really nice, thank you! This would be an STL Tech logo. :)

**Comment by BrianHicks** [comment]
Closing, we're using the city of St. Louis flag for now.
